server:
  port: 8081
spring:
  application:
    name: eureka-client-provider
eureka:
  client:
    service-url:
      default-zone: http://eureka8761:8761/eureka/,http://eureka8762:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}


